---
# generic settings
main_username: alex
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# ferrarimarco.bash-aliases
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' "}
  - { alias: "dstop", command: "docker stop `docker ps -aq`"}
  - { alias: "drm", command: "docker rm `docker ps -aq`"}
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml "}
  - { alias: "dcporph", command: "docker-compose -f ~/docker-compose.yml --remove-orphans "}
  - { alias: "dprune", command: "docker image prune"}
  - { alias: "dprunesys", command: "docker system prune --all"}
  - { alias: "bashreload", command: "source ~/.bashrc && echo Bash config reloaded;"}
  - { alias: "ctop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock http://quay.io/vektorlab/ctop "}
  - { alias: "sshclear", command: "rm ~/.ssh/multiplex/* -f && echo SSH connection cache cleared;"}
  - { alias: "sshlist", command: "echo Currently open ssh connections && echo && l ~/.ssh/multiplex/"}
  - { alias: "dfclean", command: "df -h -x tmpfs -x zfs -t fuse.mergerfs -t xfs -t ext4"}
  - { alias: "dfzfs", command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 -t zfs"}

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: mutt
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: open-vm-tools
  - name: python
  - name: qemu-guest-agent
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# ironicbadger.ansible_users
users:
  - username: "{{ main_username }}"
    github_username: ironicbadger
    name: "{{ main_username }}"
    groups: ['wheel']
    uid: "{{ main_uid }}"
groups_to_create:
  - name: "{{ main_groupname }}"
    gid: "{{ main_gid }}"
  - name: wheel

# weareinteractive.environment
environment_config: {
  "PUID": "{{ main_gid }}",
  "PGID": "{{ main_gid }}"
}
# geerlingguy.ntp
ntp_timezone: "America/New_York"

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_sudoers_passwordless:
  - alex

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /home/alex

# influxdb
influxdb_ip: 192.168.1.10
influxdb_port: 8086

## telegraf
telegraf_influxdb_urls:
  - "http://{{ influxdb_ip }}:{{ influxdb_port }}"
telegraf_influxdb_database: telegraf
telegraf_influxdb_username: root
telegraf_influxdb_password: root
telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      collect_cpu_time: "false"
      report_active: "false"
  - name: disk
    options:
      ignore_fs:
        - "tmpfs"
        - "devtmpfs"
        - "devfs"
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: kernel
  - name: processes
  - name: docker
    options:
      endpoint: "unix:///var/run/docker.sock"
      perdevice: "true"
  - name: hddtemp
  - name: net
    options:
      interfaces:
        - "ens192"
  - name: sensors
