services:
  ktz-garage-ts:
    image: tailscale/tailscale:latest
    container_name: ktz-garage-ts
    hostname: garage
    environment:
      - "TS_AUTHKEY={{ tailscale_oauth_client_secret }}?ephemeral=false"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
    volumes:
      - "{{ appdata_path }}/ktz-garage/ts-state:/var/lib/tailscale"
      - "{{ appdata_path }}/ktz-garage/ts-config:/config"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  ktz-garage:
    image: dxflrs/garage:v2.2.0
    container_name: ktz-garage
    network_mode: service:ktz-garage-ts
    depends_on:
      - ktz-garage-ts
    environment:
      - RUST_LOG=garage=info
    volumes:
      - "{{ appdata_path }}/ktz-garage/config/garage.toml:/etc/garage.toml:ro"
      - "{{ appdata_path }}/ktz-garage/data:/var/lib/garage/data"
      - "{{ appdata_path }}/ktz-garage/meta/:/var/lib/garage/meta"
    restart: unless-stopped
