services:
  # arrrrrrrrrrrrrrrrr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    volumes:
      - "{{ appdata_path }}/arrmatey/prowlarr:/config"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.{{ m_wd_domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - "{{ appdata_path }}/arrmatey/sabnzbd:/config"
      - "{{ download_path }}:/downloads"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.{{ m_wd_domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    depends_on:
      - prowlarr
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - "{{ appdata_path }}/arrmatey/sonarr:/config"
      - "{{ download_path }}/complete/tv:/downloads/complete/tv"
      - "{{ storage_path }}/media/tv:/tv"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.{{ m_wd_domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    depends_on:
      - prowlarr
      - sabnzbd
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - "{{ appdata_path }}/arrmatey/radarr:/config"
      - "{{ download_path }}/complete/movies:/downloads/complete/movies"
      - "{{ storage_path }}/media/movies:/movies"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.radarr.rule=Host(`radarr.{{ m_wd_domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    depends_on:
      - prowlarr
      - sabnzbd
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    volumes:
      - "{{ appdata_path }}/arrmatey/lidarr:/config"
      - "{{ download_path }}/complete/music:/downloads/complete/music"
      - /mnt/rust/media/music/library:/music/library
    labels:
      - traefik.enable=true
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.{{ m_wd_domain_me }}`)"
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    depends_on:
      - prowlarr
      - sabnzbd
    restart: unless-stopped
  qbit:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbit
    network_mode: service:gluetun
    volumes:
      - "{{ appdata_path }}/arrmatey/qbit:/config"
      - "{{ download_path }}:/downloads"
    depends_on:
      - gluetun
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
      - WEBUI_PORT=8080
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    labels:
      - traefik.enable=true
      - "traefik.http.routers.gluetun.rule=Host(`qbit.{{ m_wd_domain_me }}`)"
      - traefik.http.services.gluetun.loadbalancer.server.port=8080
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - "{{ appdata_path }}/arrmatey/gluetun:/gluetun"
    environment:
      - "TZ={{ host_timezone }}"
      - VPN_SERVICE_PROVIDER=privado
      - VPN_TYPE=openvpn
      - "OPENVPN_USER={{ gluetun_privado_username }}"
      - "OPENVPN_PASSWORD={{ gluetun_privado_password }}"
    restart: unless-stopped
  seerr:
    image: ghcr.io/seerr-team/seerr:develop
    container_name: seerr
    volumes:
      - "{{ appdata_path }}/arrmatey/seerr:/app/config"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.seerr.rule=Host(`seerr.{{ m_wd_domain_me }}`)"
    restart: unless-stopped
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    volumes:
      - "{{ appdata_path }}/arrmatey/shelfmark:/config"
      - "{{ storage_path }}/media/books:/books"
      - "{{ download_path }}/complete/books:/downloads"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.shelfmark.rule=Host(`shelfmark.{{ m_wd_domain_me }}`)"
      - traefik.http.services.shelfmark.loadbalancer.server.port=8084
    environment:
      - "PUID={{ docker_compose_generator_uid }}"
      - "PGID={{ docker_compose_generator_gid }}"
      - "TZ={{ host_timezone }}"
    restart: unless-stopped
