---
- name: ensure target dir exists
  file:
    dest: "{{ appdata_path }}/short/traefik/"
    state: directory
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"

- name: template traefik config
  template:
    src: templates/traefik.yaml.j2
    dest: "{{ appdata_path }}/short/traefik/traefik.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  tags: traefik

- name: copy traefik rules
  template:
    src: templates/rules.yaml.j2
    dest: "{{ appdata_path }}/short/traefik/rules.yaml"
    owner: "{{ main_uid }}"
    group: "{{ main_gid }}"
  when: traefik_file_provider
  tags: traefik