---

- name: ensure python pip is available
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: install apprise
  ansible.builtin.pip:
    name: apprise
  become: true

- name: install script that cron will execute
  ansible.builtin.template:
    src: booted.sh.j2
    dest: /root/booted.sh
    owner: root
    group: root
    mode: '700'

- name: install boot notification script
  ansible.builtin.cron:
    name: "boot notification to pushover"
    special_time: reboot
    job: /bin/bash /root/booted.sh
