galaxy_info:
  role_name: caddy
  author: ironicbadger
  description: Ansible role for Caddy
  license: MIT
  min_ansible_version: "2.4"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - debian
    - ubuntu
    - caddy

dependencies: []