---

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items: 
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ extra_mountpoints }}"

- name: mount disks
  mount:
    name: "{{ item.path }}"
    src: "{{ item.diskbyid }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ extra_mountpoints }}"
  when: item.path != '/mnt/storage'


- name: mount mergerfs array
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.source }}"
    opts: "{{ item.opts }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - "{{ fstab_mergerfs }}"