---
core_network_interface: "eth0"
core_ipv4_prefix: 21
core_ipv4_gateway: "10.42.0.254"
core_dns_servers:
  - "1.1.1.1"
  - "1.0.0.1"

core_vip_cidr: "10.42.0.53/21"
keepalived_instance_name: "VI_DNS"
keepalived_router_id: 53
keepalived_auth_pass: "change-me"
keepalived_advert_interval: 1
keepalived_check_interval: 2

chrony_pools:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"

adguard_version: "0.107.51"
adguard_install_dir: "/opt/adguardhome"
adguard_config_dir: "/etc/adguardhome"
adguard_work_dir: "/var/lib/adguardhome"
adguard_config_src: ""
# Example: "{{ playbook_dir }}/../files/adguardhome/AdGuardHome.yaml"
adguard_config_dest: "/etc/adguardhome/AdGuardHome.yaml"
